//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casos
    {
        public int Id { get; set; }
        public string TipoDeCrimen { get; set; }
        public string Detalles { get; set; }
        public string Documento { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
